### ISSUE TITLE
Bug: 로그인 화면 UI 수정

### ISSUE THREAD

**Issue by hyorish03** [wldnjs7064/react-firebase-chat-app#27]
### 문제상황
- 로그인 화면 보면 UI가 깨지네요
- 수정이 필요할 것 같습니다 !

### 참고이미지
<img width="1800" alt="image" src="https://github.com/wldnjs7064/react-firebase-chat-app/assets/108210492/55258d6d-8721-4888-a21e-7de67ffbb88b">

**Comment by wldnjs7064** [comment]
수정 완료 했습니다!
